const DEFAULT_45_ADVISORS = [
  // OSMANLI (15 Aday)
  { id:"adv_os_1", name:"Kâtip Hamdi Efendi", role:"Defterhane Çırağı", stars:1, salary:12000, targetName:"Osmanlı İmparatorluğu", buff:"+%1 Vergi Geliri", debuff:"Bina yapımı +%1 pahalı.", taxBonus:1, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:-1, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:2, maxAge:15, yearsSinceUpgrade:0 },
  { id:"adv_os_2", name:"Topçu Kalfası Veli", role:"Tophane Dökümcüsü", stars:1, salary:15000, targetName:"Osmanlı İmparatorluğu", buff:"-%2 Topçu Bakımı", debuff:"Ordu bakımı +%1.", taxBonus:0, milUpkeepDiscount:-1, navyUpkeepDiscount:0, artUpkeepDiscount:2, recruitDiscount:0, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:3, maxAge:18, yearsSinceUpgrade:0 },
  { id:"adv_os_3", name:"Derviş Cemal", role:"Tekke Dervişi", stars:1, salary:10000, targetName:"Osmanlı İmparatorluğu", buff:"+1 Mutluluk", debuff:"Elverişli nüfus -200.", taxBonus:0, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:1, stopAnarchy:false, spyAccuracyBonus:false, ageYears:5, maxAge:22, yearsSinceUpgrade:0 },
  { id:"adv_os_4", name:"Subaşı Bahadır Ağa", role:"Asayiş Zabiti", stars:2, salary:25000, targetName:"Osmanlı İmparatorluğu", buff:"Anarşistlerin zararını %25 azaltır.", debuff:"Mutluluk -1 puan.", taxBonus:0, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:-1, stopAnarchy:false, spyAccuracyBonus:false, ageYears:4, maxAge:20, yearsSinceUpgrade:0 },
  { id:"adv_os_5", name:"Reis İlyas", role:"Kadırga Kaptanı", stars:2, salary:30000, targetName:"Osmanlı İmparatorluğu", buff:"-%3 Donanma Bakımı", debuff:"Ticaret -%1.", taxBonus:-1, milUpkeepDiscount:0, navyUpkeepDiscount:3, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:6, maxAge:25, yearsSinceUpgrade:0 },
  { id:"adv_os_6", name:"Mimar Şükrü Çelebi", role:"Hassa Mimarı", stars:2, salary:28000, targetName:"Osmanlı İmparatorluğu", buff:"-%3 Bina Yapım Maliyeti", debuff:"Yıllık 3.000 TL şantiye masrafı.", taxBonus:0, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:3, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:5, maxAge:24, yearsSinceUpgrade:0 },
  { id:"adv_os_7", name:"Defterdar Muhsin Paşa", role:"Sıkı Muhasebeci", stars:3, salary:50000, targetName:"Osmanlı İmparatorluğu", buff:"+%4 Vergi Geliri", debuff:"Mutluluk -2 puan.", taxBonus:4, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:-2, stopAnarchy:false, spyAccuracyBonus:false, ageYears:7, maxAge:28, yearsSinceUpgrade:0 },
  { id:"adv_os_8", name:"Kurt Ali Ağa", role:"Kışla Ağası", stars:3, salary:55000, targetName:"Osmanlı İmparatorluğu", buff:"-%5 Asker Satın Alma İndirimi", debuff:"Piyade bakımı +%2.", taxBonus:0, milUpkeepDiscount:-2, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:5, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:8, maxAge:26, yearsSinceUpgrade:0 },
  { id:"adv_os_9", name:"Kuşçubaşı Seyfi Efendi", role:"Divan İstihbaratçısı", stars:3, salary:48000, targetName:"Osmanlı İmparatorluğu", buff:"Casusluk Yanılmasını %10'a düşürür.", debuff:"İstihbarat bütçesi çeker.", taxBonus:0, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:true, ageYears:4, maxAge:22, yearsSinceUpgrade:0 },
  { id:"adv_os_10", name:"Kaptan-ı Derya Turgut Paşa", role:"Denizler Fatihi", stars:4, salary:85000, targetName:"Osmanlı İmparatorluğu", buff:"-%6 Donanma Bakımı & -%4 Gemi Alımı", debuff:"Ticaret geliri -%2.", taxBonus:-2, milUpkeepDiscount:0, navyUpkeepDiscount:6, artUpkeepDiscount:0, recruitDiscount:4, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:10, maxAge:30, yearsSinceUpgrade:0 },
  { id:"adv_os_11", name:"Dökümcübaşı Urbanzade", role:"Büyük Şahi Topçusu", stars:4, salary:90000, targetName:"Osmanlı İmparatorluğu", buff:"-%7 Topçu Bakımı", debuff:"Top alım fiyatı +%3.", taxBonus:0, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:7, recruitDiscount:-3, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:9, maxAge:28, yearsSinceUpgrade:0 },
  { id:"adv_os_12", name:"Müderris Ebu Fazıl Efendi", role:"Ulema Başı", stars:4, salary:75000, targetName:"Osmanlı İmparatorluğu", buff:"+4 Mutluluk & -%3 Bina İndirimi", debuff:"Vergi toplama -%1.", taxBonus:-1, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:3, happinessBonus:4, stopAnarchy:false, spyAccuracyBonus:false, ageYears:12, maxAge:30, yearsSinceUpgrade:0 },
  { id:"adv_os_13", name:"Veziriazam Demir Köprülü Paşa", role:"Mutlak Otorite", stars:5, salary:160000, targetName:"Osmanlı İmparatorluğu", buff:"+%8 Vergi Geliri & İsyanı %0 Yapar", debuff:"Mutluluk -3 puan.", taxBonus:8, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:-3, stopAnarchy:true, spyAccuracyBonus:false, ageYears:14, maxAge:30, yearsSinceUpgrade:0 },
  { id:"adv_os_14", name:"Serdar-ı Ekrem Zafer Sinan Paşa", role:"Cihan Komutanı", stars:5, salary:150000, targetName:"Osmanlı İmparatorluğu", buff:"-%8 Ordu Bakımı & -%5 Sefer İkmali", debuff:"Yıllık paşa harcırahı ister.", taxBonus:0, milUpkeepDiscount:8, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:5, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:11, maxAge:29, yearsSinceUpgrade:0 },
  { id:"adv_os_15", name:"Hazine Nazırı Karun Efendi", role:"Mali Deha", stars:5, salary:140000, targetName:"Osmanlı İmparatorluğu", buff:"+%10 Vergi Geliri", debuff:"Komisyon keser.", taxBonus:10, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:13, maxAge:30, yearsSinceUpgrade:0 },

  // KIRIM HANLIĞI (15 Aday)
  { id:"adv_kr_1", name:"Otlakçı Timur Ağa", role:"Bozkır Seyisi", stars:1, salary:10000, targetName:"Kırım Hanlığı", buff:"-%2 Süvari/Ordu Bakımı", debuff:"Bina yapımı +%1.", taxBonus:0, milUpkeepDiscount:2, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:-1, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:3, maxAge:16, yearsSinceUpgrade:0 },
  { id:"adv_kr_2", name:"Kefe Kâtibi Canbek", role:"Liman Kâtibi", stars:1, salary:12000, targetName:"Kırım Hanlığı", buff:"+%2 Sabit Ticaret Geliri", debuff:"Kâtip harcı çeker.", taxBonus:2, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:4, maxAge:18, yearsSinceUpgrade:0 },
  { id:"adv_kr_3", name:"İzci Tohtamış", role:"Öncü İzci", stars:1, salary:11000, targetName:"Kırım Hanlığı", buff:"-%2 Asker Satın Alma İndirimi", debuff:"Ordu disiplini hafif düşer.", taxBonus:0, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:2, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:2, maxAge:15, yearsSinceUpgrade:0 },
  { id:"adv_kr_4", name:"Yay Ustası Cihanşa", role:"Bozkır Silahçısı", stars:2, salary:22000, targetName:"Kırım Hanlığı", buff:"-%3 Ordu Bakımı", debuff:"Asker alımı +%1 pahalanır.", taxBonus:0, milUpkeepDiscount:3, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:-1, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:5, maxAge:22, yearsSinceUpgrade:0 },
  { id:"adv_kr_5", name:"Arslan Bey", role:"Saray Sözcüsü", stars:2, salary:25000, targetName:"Kırım Hanlığı", buff:"+2 Mutluluk", debuff:"Ziyafet masrafı çeker.", taxBonus:0, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:2, stopAnarchy:false, spyAccuracyBonus:false, ageYears:6, maxAge:24, yearsSinceUpgrade:0 },
  { id:"adv_kr_6", name:"Mamay Reis", role:"Nehir Kaptanı", stars:2, salary:26000, targetName:"Kırım Hanlığı", buff:"-%4 Donanma Bakımı", debuff:"Ticaret -%1.", taxBonus:-1, milUpkeepDiscount:0, navyUpkeepDiscount:4, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:7, maxAge:25, yearsSinceUpgrade:0 },
  { id:"adv_kr_7", name:"Ataman Bahadır Mirza", role:"Bozkır Süvari Ağası", stars:3, salary:45000, targetName:"Kırım Hanlığı", buff:"-%5 Ordu Bakımı & -%4 Asker Alımı", debuff:"Otlak harcırahı ister.", taxBonus:0, milUpkeepDiscount:5, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:4, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:8, maxAge:26, yearsSinceUpgrade:0 },
  { id:"adv_kr_8", name:"Hacı Mengli Sarraf", role:"Tüccar Başı", stars:3, salary:48000, targetName:"Kırım Hanlığı", buff:"+%5 Vergi Geliri", debuff:"Komisyon keser.", taxBonus:5, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:9, maxAge:27, yearsSinceUpgrade:0 },
  { id:"adv_kr_9", name:"Gözcü Şahin Noyan", role:"Bozkır Casusu", stars:3, salary:42000, targetName:"Kırım Hanlığı", buff:"Casusluk Yanılmasını %10'a çeker.", debuff:"Mektup diplomasisi -%1.", taxBonus:0, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:true, ageYears:5, maxAge:23, yearsSinceUpgrade:0 },
  { id:"adv_kr_10", name:"Nogay Beyi Korkut Han", role:"Çöl Kurdu", stars:4, salary:75000, targetName:"Kırım Hanlığı", buff:"-%6 Ordu Bakımı", debuff:"Ticaret -%2.", taxBonus:-2, milUpkeepDiscount:6, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:11, maxAge:30, yearsSinceUpgrade:0 },
  { id:"adv_kr_11", name:"Mimar İlyas", role:"Tahkimat Ustası", stars:4, salary:70000, targetName:"Kırım Hanlığı", buff:"-%6 Bina Yapım İndirimi", debuff:"Şantiye gideri çeker.", taxBonus:0, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:6, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:10, maxAge:29, yearsSinceUpgrade:0 },
  { id:"adv_kr_12", name:"Müftü Abdülmecid", role:"Bozkır Şeyhi", stars:4, salary:65000, targetName:"Kırım Hanlığı", buff:"+4 Mutluluk & İsyanı %50 Azaltır", debuff:"Vergi -%1.", taxBonus:-1, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:4, stopAnarchy:false, spyAccuracyBonus:false, ageYears:12, maxAge:30, yearsSinceUpgrade:0 },
  { id:"adv_kr_13", name:"Han Naibi Mengli Atalık", role:"Hanlık Aklı", stars:5, salary:130000, targetName:"Kırım Hanlığı", buff:"+%8 Vergi Geliri & İsyanı %0 Yapar", debuff:"Saray ödeneği ister.", taxBonus:8, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:0, stopAnarchy:true, spyAccuracyBonus:false, ageYears:14, maxAge:30, yearsSinceUpgrade:0 },
  { id:"adv_kr_14", name:"Gazi Alp Serdar", role:"Efsane Akıncı", stars:5, salary:125000, targetName:"Kırım Hanlığı", buff:"-%9 Ordu Bakımı & -%5 Sefer İkmali", debuff:"Topçu bakımı +%3.", taxBonus:0, milUpkeepDiscount:9, navyUpkeepDiscount:0, artUpkeepDiscount:-3, recruitDiscount:5, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:11, maxAge:28, yearsSinceUpgrade:0 },
  { id:"adv_kr_15", name:"Sarraf Karahan", role:"Altın Kervancısı", stars:5, salary:120000, targetName:"Kırım Hanlığı", buff:"+%10 Vergi Geliri", debuff:"Mutluluk -2 puan.", taxBonus:10, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:-2, stopAnarchy:false, spyAccuracyBonus:false, ageYears:13, maxAge:30, yearsSinceUpgrade:0 },

  // GÜNEŞ DEVLETİ (15 Aday)
  { id:"adv_gn_1", name:"Çavuş Bora", role:"Sert Kollukçu", stars:1, salary:10000, targetName:"Güneş Devleti", buff:"-%2 Ordu Bakımı", debuff:"Mutluluk -1 puan.", taxBonus:0, milUpkeepDiscount:2, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:-1, stopAnarchy:false, spyAccuracyBonus:false, ageYears:3, maxAge:16, yearsSinceUpgrade:0 },
  { id:"adv_gn_2", name:"Körük Ustası Kaya", role:"Küçük Ocakçı", stars:1, salary:12000, targetName:"Güneş Devleti", buff:"-%2 Topçu Bakımı", debuff:"Top alımı +%1.", taxBonus:0, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:2, recruitDiscount:-1, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:4, maxAge:17, yearsSinceUpgrade:0 },
  { id:"adv_gn_3", name:"Tellal Selim", role:"Halk Kışkırtıcısı", stars:1, salary:11000, targetName:"Güneş Devleti", buff:"+1 Mutluluk", debuff:"Şehir asayiş masrafı çeker.", taxBonus:0, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:1, stopAnarchy:false, spyAccuracyBonus:false, ageYears:2, maxAge:15, yearsSinceUpgrade:0 },
  { id:"adv_gn_4", name:"Tahsildar Demir", role:"Acımasız Tahsildar", stars:2, salary:24000, targetName:"Güneş Devleti", buff:"+%3 Vergi Geliri", debuff:"Mutluluk -1 puan.", taxBonus:3, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:-1, stopAnarchy:false, spyAccuracyBonus:false, ageYears:5, maxAge:22, yearsSinceUpgrade:0 },
  { id:"adv_gn_5", name:"Yaman Reis", role:"Kıyı Muhafızı", stars:2, salary:26000, targetName:"Güneş Devleti", buff:"-%3 Donanma Bakımı", debuff:"Gemi yapımı +%2.", taxBonus:0, milUpkeepDiscount:0, navyUpkeepDiscount:3, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:-2, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:6, maxAge:24, yearsSinceUpgrade:0 },
  { id:"adv_gn_6", name:"Rükneddin Kalfa", role:"Cevher Arayıcı", stars:2, salary:25000, targetName:"Güneş Devleti", buff:"-%3 Bina Yapım İndirimi", debuff:"Şantiye masrafı çeker.", taxBonus:0, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:3, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:5, maxAge:23, yearsSinceUpgrade:0 },
  { id:"adv_gn_7", name:"Kara Kurt", role:"Korku Mimarı", stars:3, salary:48000, targetName:"Güneş Devleti", buff:"Anarşistlerin zararını %30 azaltır.", debuff:"Mutluluk -2 puan.", taxBonus:0, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:-2, stopAnarchy:false, spyAccuracyBonus:false, ageYears:8, maxAge:26, yearsSinceUpgrade:0 },
  { id:"adv_gn_8", name:"Alp Erdem", role:"Disiplin Subayı", stars:3, salary:52000, targetName:"Güneş Devleti", buff:"-%5 Ordu Bakımı", debuff:"Asker alım fiyatı +%2.", taxBonus:0, milUpkeepDiscount:5, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:-2, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:9, maxAge:27, yearsSinceUpgrade:0 },
  { id:"adv_gn_9", name:"Sarraf Leon", role:"Gölge Banker", stars:3, salary:46000, targetName:"Güneş Devleti", buff:"+%5 Vergi Geliri", debuff:"Faiz kesintisi yapar.", taxBonus:5, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:7, maxAge:25, yearsSinceUpgrade:0 },
  { id:"adv_gn_10", name:"Sadrazam Oğuz Bey", role:"Devlet Direği", stars:4, salary:80000, targetName:"Güneş Devleti", buff:"Anarşiyi %0 Yapar & +%4 Vergi", debuff:"Mutluluk -3 puan.", taxBonus:4, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:-3, stopAnarchy:true, spyAccuracyBonus:false, ageYears:11, maxAge:30, yearsSinceUpgrade:0 },
  { id:"adv_gn_11", name:"Mühendis Hektor", role:"Top Döküm Üstadı", stars:4, salary:78000, targetName:"Güneş Devleti", buff:"-%7 Topçu Bakımı", debuff:"Top alım fiyatı +%3.", taxBonus:0, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:7, recruitDiscount:-3, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:10, maxAge:29, yearsSinceUpgrade:0 },
  { id:"adv_gn_12", name:"Baybars Casus Başı", role:"Gizli Ağ Ustası", stars:4, salary:72000, targetName:"Güneş Devleti", buff:"Casusluk Yanılmasını %5'e çeker.", debuff:"Casus maaşı çeker.", taxBonus:0, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:true, ageYears:9, maxAge:28, yearsSinceUpgrade:0 },
  { id:"adv_gn_13", name:"Baş Vezir Nizamüddin", role:"Tiranlığın Mimarı", stars:5, salary:145000, targetName:"Güneş Devleti", buff:"+%8 Vergi & -%5 Bina İndirimi & İsyan %0", debuff:"Mutluluk -3 puan.", taxBonus:8, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:5, happinessBonus:-3, stopAnarchy:true, spyAccuracyBonus:false, ageYears:13, maxAge:30, yearsSinceUpgrade:0 },
  { id:"adv_gn_14", name:"Cihangir Han Mareşal", role:"Yenilmez Mareşal", stars:5, salary:140000, targetName:"Güneş Devleti", buff:"-%8 Ordu Bakımı & -%6 Asker Alımı", debuff:"Sefer ikramiyesi ister.", taxBonus:0, milUpkeepDiscount:8, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:6, infraDiscount:0, happinessBonus:0, stopAnarchy:false, spyAccuracyBonus:false, ageYears:12, maxAge:30, yearsSinceUpgrade:0 },
  { id:"adv_gn_15", name:"Karun Mirza", role:"Altın Simyacısı", stars:5, salary:130000, targetName:"Güneş Devleti", buff:"+%10 Vergi Geliri", debuff:"Mutluluk -3 puan.", taxBonus:10, milUpkeepDiscount:0, navyUpkeepDiscount:0, artUpkeepDiscount:0, recruitDiscount:0, infraDiscount:0, happinessBonus:-3, stopAnarchy:false, spyAccuracyBonus:false, ageYears:14, maxAge:30, yearsSinceUpgrade:0 }
];

// ---------------- RASTGELE OLAY SİSTEMİ ----------------
const EVENT_CATEGORIES = [
 {name:"Kuraklık", title:["Büyük Kuraklık","Uzayan Kuraklık","Ambarları Zorlayan Kuraklık","Tarlalarda Su Sıkıntısı","Kuruyan Nehirler"]},
 {name:"Ticaret", title:["Ticaret Kervanları","Liman Ticareti","Yeni Pazarlar","Tüccarların Şikâyeti","Ticaret Fırsatı"]},
 {name:"Halk", title:["Halk Şenliği","Vergi İsyanı","Esnaf Grevi","Şehir Kalabalığı","Halkın Talebi"]},
 {name:"Askeri", title:["Sınır Çatışması","Askeri Depo Sorunu","Hudut Garnizonu","Silah Ustalarının Talebi","Orduda Disiplin Sorunu"]},
 {name:"Doğa", title:["Büyük Sel","Şiddetli Fırtına","Erken Kış","Deprem Sarsıntısı","Orman Yangını"]},
 {name:"Diplomasi", title:["Yabancı Elçiler","Komşu Devletin Teklifi","Sınır Anlaşmazlığı","Tüccar Elçileri","Diplomatik Kriz"]},
 {name:"Üretim", title:["Maden Damarlari","Zanaatkârların Talebi","Yeni Atölyeler","Tahıl Fazlası","Üretim Darboğazı"]},
 {name:"Saray", title:["Saray Masrafları","Soylu Ailelerin Talebi","Taç Töreni","Saray Ziyafeti","Divan Tartışması"]},
 {name:"Sağlık", title:["Şehirde Hastalık","Hekimlerin Uyarısı","Şifa Evleri","Temizlik Kampanyası","Karantina Tartışması"]},
 {name:"Altyapı", title:["Köprü Hasarı","Yol Bakımı","Liman Onarımı","Su Kemerleri","Pazar Meydanı"]},
 {name:"Eğitim", title:["Müderrislerin Talebi","Yeni Mektep","Kütüphane Fırsatı","Bilginlerin Gelişi","Âlimlerin İsteği"]},
 {name:"Güvenlik", title:["Eşkiya Baskını","Şehir Güvenliği","Gece Devriyeleri","Kaçakçılık","Sınırda Haydutlar"]},
 {name:"Tarım", title:["Bereketli Hasat","Çiftçi Borçları","Tohum Sıkıntısı","Hayvan Salgını","Yeni Tarım Usulü"]},
 {name:"Maliye", title:["Hazine Açığı","Vergi Tahsildarları","Sikke Sorunu","Borç Talebi","Beklenmedik Gelir"]},
 {name:"Denizcilik", title:["Fırtınalı Sefer","Tersane İhtiyacı","Deniz Tüccarları","Gemi Kazası","Yeni Deniz Rotası"]},
 {name:"Kültür", title:["Büyük Şenlik","Sanatkârların Gelişi","Saray Sanatçıları","Anıt Talebi","Halk Oyunları"]},
 {name:"Din", title:["Manevi Yardım","İbadethane Talebi","Din Âlimleri","Vakıf İsteği","Bayram Hazırlıkları"]},
 {name:"Nüfus", title:["Göçmenler Geldi","Şehirden Göç","Yeni Mahalle","Nüfus Baskısı","Yerleşim Fırsatı"]},
 {name:"Casusluk", title:["Şüpheli Haberler","Yabancı Casuslar","Gizli Belgeler","İstihbarat Fırsatı","Saraydaki Fısıltılar"]},
 {name:"İsyan", title:["Taşrada Huzursuzluk","Yerel İsyan","Soylu Muhalefeti","Köylülerin Protestosu","Şehir Ayaklanması"]}
];
const EVENT_A_TEXTS=["Kaynak ayır ve halkı destekle","Hemen müdahale et","Devlet hazinesinden ödeme yap","Uzlaşma yolunu seç","Devlet desteğini artır"];
const EVENT_B_TEXTS=["Masrafı reddet ve bekle","Sert tedbirler uygula","Harcamayı sınırlı tut","Talebi geri çevir","Yerel yöneticilere bırak"];
