create table if not exists public.game_state (
  id bigint primary key,
  data jsonb not null default '{"states":[],"settings":{},"transfers":[]}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.game_state enable row level security;

drop policy if exists "authenticated can read game state" on public.game_state;
create policy "authenticated can read game state" on public.game_state for select to authenticated using (true);

drop policy if exists "authenticated can insert game state" on public.game_state;
create policy "authenticated can insert game state" on public.game_state for insert to authenticated with check (true);

drop policy if exists "authenticated can update game state" on public.game_state;
create policy "authenticated can update game state" on public.game_state for update to authenticated using (true) with check (true);

grant select, insert, update on public.game_state to authenticated;

insert into public.game_state(id,data) values (1,'{"states":[],"settings":{},"transfers":[]}'::jsonb) on conflict(id) do nothing;


-- Eşzamanlı kayıt güvenliği ve geri kazanılabilir snapshotlar
alter table public.game_state add column if not exists revision bigint not null default 1;

create table if not exists public.game_state_snapshots (
  id bigint generated by default as identity primary key,
  game_state_id bigint not null references public.game_state(id) on delete cascade,
  data jsonb not null,
  source text not null default 'manual',
  created_at timestamptz not null default now()
);

alter table public.game_state_snapshots enable row level security;
grant select, insert on public.game_state_snapshots to authenticated;

drop policy if exists "authenticated can read snapshots" on public.game_state_snapshots;
create policy "authenticated can read snapshots" on public.game_state_snapshots for select to authenticated using (true);

drop policy if exists "authenticated can create snapshots" on public.game_state_snapshots;
create policy "authenticated can create snapshots" on public.game_state_snapshots for insert to authenticated with check (true);

create or replace function public.save_game_state(expected_revision bigint, next_data jsonb)
returns table(saved_revision bigint, saved_updated_at timestamptz)
language sql
set search_path = public
as $$
  update public.game_state
     set data = next_data,
         revision = revision + 1,
         updated_at = now()
   where id = 1
     and revision = expected_revision
  returning revision, updated_at;
$$;

grant execute on function public.save_game_state(bigint, jsonb) to authenticated;
